-- Analista por filial (CORRIGIDO). Filial inexistente é ignorada.

update env_destinos set analista = 'Administrativo' where filial = '473';
update env_destinos set analista = 'Administrativo' where filial = '472';
update env_destinos set analista = 'Administrativo' where filial = '85';
update env_destinos set analista = 'Administrativo' where filial = '380';
update env_destinos set analista = 'Administrativo' where filial = '455';
update env_destinos set analista = 'Administrativo' where filial = '535';
update env_destinos set analista = 'Administrativo' where filial = '428';
update env_destinos set analista = 'Amanda Menezes' where filial = '422';
update env_destinos set analista = 'Amanda Menezes' where filial = '435';
update env_destinos set analista = 'Amanda Menezes' where filial = '476';
update env_destinos set analista = 'Amanda Menezes' where filial = '448';
update env_destinos set analista = 'Amanda Menezes' where filial = '417';
update env_destinos set analista = 'Administrativo' where filial = '441';
update env_destinos set analista = 'Administrativo' where filial = '414';
update env_destinos set analista = 'Amanda Menezes' where filial = '471';
update env_destinos set analista = 'Amanda Menezes' where filial = '510';
update env_destinos set analista = 'Administrativo' where filial = '431';
update env_destinos set analista = 'Raquel França' where filial = '260';
update env_destinos set analista = 'Raquel França' where filial = '281';
update env_destinos set analista = 'Raquel França' where filial = '251';
update env_destinos set analista = 'Isabela Costa' where filial = '464';
update env_destinos set analista = 'Administrativo' where filial = '484';
update env_destinos set analista = 'Administrativo' where filial = '528';
update env_destinos set analista = 'Administrativo' where filial = '522';
update env_destinos set analista = 'Administrativo' where filial = '395';
update env_destinos set analista = 'Administrativo' where filial = '396';
update env_destinos set analista = 'Amanda Menezes' where filial = '468';
update env_destinos set analista = 'Amanda Menezes' where filial = '452';
update env_destinos set analista = 'Suiane Lopes' where filial = '155';
update env_destinos set analista = 'Suiane Lopes' where filial = '442';
update env_destinos set analista = 'Raquel França' where filial = '86';
update env_destinos set analista = 'Raquel França' where filial = '451';
update env_destinos set analista = 'Suiane Lopes' where filial = '463';
update env_destinos set analista = 'Suiane Lopes' where filial = '474';
update env_destinos set analista = 'Suiane Lopes' where filial = '477';
update env_destinos set analista = 'Suiane Lopes' where filial = '413';
update env_destinos set analista = 'Administrativo' where filial = '512';
update env_destinos set analista = 'Administrativo' where filial = '509';
update env_destinos set analista = 'Administrativo' where filial = '268';
update env_destinos set analista = 'Administrativo' where filial = '490';
update env_destinos set analista = 'Administrativo' where filial = '404';
update env_destinos set analista = 'Suiane Lopes' where filial = '447';
update env_destinos set analista = 'Suiane Lopes' where filial = '516';
update env_destinos set analista = 'Suiane Lopes' where filial = '459';
update env_destinos set analista = 'Administrativo' where filial = '264';
update env_destinos set analista = 'Raquel França' where filial = '488';
update env_destinos set analista = 'Raquel França' where filial = '421';
update env_destinos set analista = 'Raquel França' where filial = '245';
update env_destinos set analista = 'Administrativo' where filial = '439';
update env_destinos set analista = 'Raquel França' where filial = '156';
update env_destinos set analista = 'Raquel França' where filial = '294';
update env_destinos set analista = 'Isabela Costa' where filial = '252';
update env_destinos set analista = 'Isabela Costa' where filial = '487';
update env_destinos set analista = 'Administrativo' where filial = '527';
update env_destinos set analista = 'Amanda Menezes' where filial = '231';
update env_destinos set analista = 'Amanda Menezes' where filial = '284';
update env_destinos set analista = 'Raquel França' where filial = '225';
update env_destinos set analista = 'Raquel França' where filial = '235';
update env_destinos set analista = 'Raquel França' where filial = '394';
update env_destinos set analista = 'Raquel França' where filial = '450';
update env_destinos set analista = 'Isabela Costa' where filial = '513';
update env_destinos set analista = 'Suiane Lopes' where filial = '246';
update env_destinos set analista = 'Suiane Lopes' where filial = '88';
update env_destinos set analista = 'Suiane Lopes' where filial = '290';
update env_destinos set analista = 'Suiane Lopes' where filial = '462';
update env_destinos set analista = 'Suiane Lopes' where filial = '482';
update env_destinos set analista = 'Administrativo' where filial = '508';
update env_destinos set analista = 'Administrativo' where filial = '300';
update env_destinos set analista = 'Amanda Menezes' where filial = '182';
update env_destinos set analista = 'Raquel França' where filial = '449';
update env_destinos set analista = 'Suiane Lopes' where filial = '433';
update env_destinos set analista = 'Administrativo' where filial = '177';
update env_destinos set analista = 'Amanda Menezes' where filial = '460';
update env_destinos set analista = 'Isabela Costa' where filial = '334';
update env_destinos set analista = 'Raquel França' where filial = '331';
update env_destinos set analista = 'Raquel França' where filial = '234';
update env_destinos set analista = 'Raquel França' where filial = '456';
update env_destinos set analista = 'Raquel França' where filial = '511';
update env_destinos set analista = 'Amanda Menezes' where filial = '485';
update env_destinos set analista = 'Amanda Menezes' where filial = '479';
update env_destinos set analista = 'Amanda Menezes' where filial = '405';
update env_destinos set analista = 'Amanda Menezes' where filial = '393';
update env_destinos set analista = 'Suiane Lopes' where filial = '248';
update env_destinos set analista = 'Suiane Lopes' where filial = '263';
update env_destinos set analista = 'Suiane Lopes' where filial = '83';
update env_destinos set analista = 'Suiane Lopes' where filial = '318';
update env_destinos set analista = 'Suiane Lopes' where filial = '115';
update env_destinos set analista = 'Administrativo' where filial = '534';
update env_destinos set analista = 'Isabela Costa' where filial = '491';
update env_destinos set analista = 'Isabela Costa' where filial = '381';
update env_destinos set analista = 'Isabela Costa' where filial = '529';
update env_destinos set analista = 'Isabela Costa' where filial = '320';
update env_destinos set analista = 'Isabela Costa' where filial = '443';
update env_destinos set analista = 'Isabela Costa' where filial = '483';
update env_destinos set analista = 'Isabela Costa' where filial = '507';
update env_destinos set analista = 'Administrativo' where filial = '423';
update env_destinos set analista = 'Isabela Costa' where filial = '416';
update env_destinos set analista = 'Isabela Costa' where filial = '486';
update env_destinos set analista = 'Isabela Costa' where filial = '285';
update env_destinos set analista = 'Isabela Costa' where filial = '38';
